name: Generate Snake Animation

on:
  schedule:
    # Executa automaticamente TODO DIA À MEIA-NOITE (UTC)
    - cron: "0 0 * * *"
  # Permite executar manualmente quando quiser
  workflow_dispatch:
  # Gera quando você faz push no repositório
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Generate Snake
      uses: Platane/snk@v3
      with:
        github_user_name: LucasZanellaCapitanio-dev
        # Gera DUAS versões (clara e escura)
        outputs: |
          dist/github-contribution-grid-snake.svg
          dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        
    - name: Upload Artefatos
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/
